button border now correctly sits at top of nav
UDmonia/calm-on pull request #109
Opened 2021-09-28 08:10 UTC by Sam-Park

![navbar-border-top-fix](https://user-images.githubusercontent.com/23022675/135048899-269f8de5-3d28-4812-9ccb-ca12be822b0b.png)

2021-10-10 21:42 UTC, jackzhen1996 requested changes
Good work Sam! Did you test your changes against devices of different sizes ? I checked out your branch on iPhone 11 simulator and it seems like it's still off

2021-10-14 01:43 UTC, GabrielMarquez0852 approved these changes
Looks good

2021-10-15 22:35 UTC, jackzhen1996 approved these changes
Good stuff, one thing tho can you remove the `console.log` from line 92 in `homeStack` ?

2021-10-15 23:09 UTC, Sam-Park commented
Yea for sure, sorry I missed that!

2021-10-16 12:46 UTC, merged