Checkin temp fix
UDmonia/calm-on pull request #111
Opened 2021-10-15 19:26 UTC by Sam-Park

2021-10-15 22:57 UTC, jackzhen1996 requested changes
Good work getting the check-in calendar to work! i might need some more time to review this since its a pretty big change, but can you also remove all the unused comments and `console.logs` ?

2021-10-15 22:57 UTC, jackzhen1996 commented on src/data/dummyData.js
> +        "2 Sat": [
is `2 Sat` the format we're gonna be getting from the API ?

2021-10-15 22:57 UTC, jackzhen1996 commented on src/components/Calendar.js
> +                if(checkinObject['data'][prop].length > 1){
i think we can combine line 41 and 42 into a single statement

2021-10-15 22:57 UTC, jackzhen1996 commented on src/components/checkinDetails.js
> +import React, { useEffect, useState, setState } from "react";
are we using `setState` anywhere?

2021-10-15 22:57 UTC, jackzhen1996 commented on src/components/checkinDetails.js
> +  // console.log("sprite@@@@@@@@@@@@@@@@@@@@@@@@@", spriteActivityData)
do we need the comments from line 36 to line 39?

2021-10-15 22:57 UTC, jackzhen1996 commented on src/components/previewEntries.js
> +  // capitalize function for mood as mood comes back as lowercase from Database
probably don't need the comments from line 35 to 57

2021-10-16 12:35 UTC, Sam-Park commented on src/data/dummyData.js
> +        "2 Sat": [
yes this is the data structure coming back from monthly checkins get request
![image](https://user-images.githubusercontent.com/23022675/137587617-fb477356-3888-42e7-841a-149d99944d91.png)

2021-10-16 12:43 UTC, Sam-Park commented
made changes requested, thanks Jack!

2021-11-08 00:44 UTC, jackzhen1996 approved these changes

2021-11-09 21:44 UTC, merged